version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./docker/mongo:/data/db
    restart: always
    ports:
      - 8000:27017
  # app:
  #   container_name: app-news
  #   # image: build-docker:v8
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mongo
  #   # volumes:
  #   #   - ./:/app
  #   ports:
  #     - 80:80
  #   env_file:
  #     - .env
  #   command: ["node", "index.js"]
    # links:
    #   - mongo
